### ISSUE TITLE
uptime on 6809 outputs the "\n" printed last, before anything else ???

### ISSUE THREAD

**Issue by EtchedPixels** [EtchedPixels/FUZIX#201]
wtf ?

**Comment by beretta42** [comment]
Hmmm... same exact thing happens on my coco3 port.  Here I thought it was my tty swallowing the final \n

**Comment by beretta42** [comment]
gcc is optimizing the final printf("\n") into a putchar call.  The lib's putchar (see putchar_wrapper.c)  calls write directly, thereby short-cutting the lib's buffer.  and out pops the "\n" before the rest of the line.  I changed putchar:

int putchar(int ch)
{
	return fprintf(1,"%c", ch );
}

which eliminates the pre-output line "\n", but leaves the problem of no trailing "\n"...

**Comment by EtchedPixels** [comment]
Yes it would  fprintf(stdout, ...) not 1

I think the actual problem is that the putc/getc macros are broken. They were of dubious worth anyway so I'll just replace them with unconditional use of fputc() and fgetc(). That ought to fix it.

**Comment by beretta42** [comment]
yup.. I changed the Makefile.6809 to use regular "putchar.c", rather than
"putchar_wrapper.c", and it indeed seems to work.  I haven't been able to
prove it works on dragon or dragon-nx32, but it works on coco3.

hah... the "1" must have snuck in from "write(1,...)"  :)

On Sun, Jul 19, 2015 at 4:49 PM, EtchedPixels <notifications@github.com>
wrote:

> Yes it would fprintf(stdout, ...) not 1
>
> I think the actual problem is that the putc/getc macros are broken. They
> were of dubious worth anyway so I'll just replace them with unconditional
> use of fputc() and fgetc(). That ought to fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EtchedPixels/FUZIX/issues/201#issuecomment-122706443>.
>



-- 
Brett M. Gordon,
beretta42@gmail.com
