### ISSUE TITLE
reboot leaves filesystem dirty

### ISSUE THREAD

**Issue by tormodvolden** [EtchedPixels/FUZIX#568]
Running reboot (also without -f) leaves the filesystem dirty and it will be mounted read-only on next boot. I can run "remount $ROOTDEVICE ro" before reboot, and it will be fine. Must this be handled by init scripts, or should the kernel unmount it cleanly?

BTW, after running remount, prtroot still report rw.

**Comment by EtchedPixels** [comment]
On Sat, 25 Nov 2017 18:38:18 +0000 (UTC)
Tormod Volden <notifications@github.com> wrote:

> Running reboot (also without -f) leaves the filesystem dirty and it will be mounted read-only on next boot. I can run "remount $ROOTDEVICE ro" before reboot, and it will be fine. Must this be handled by init scripts, or should the kernel unmount it cleanly?
> 
> BTW, after running remount, prtroot still report rw.
> 

init scripts

In your boot up boot with ro option
make /etc/rc run fsck / then fsck and mount any other fs (need to do
fsck -a)

My init 6 at the moment contains nothing but a script to run which does
umount -a remount / ro

Alan

**Comment by beretta42** [comment]
Fwiw:

'reboot' just calls sync and calls the platform's reboot implementation.
It alone doesnt safely shut down procs/disks.  I usually:

# shutdown
telinit 1
sleep 5
# umount -a
remount / ro
echo shutdown.
shutdown

Usually gets me close, with an occassional "dev busy" on remount (probably
some open file somewheres)

i do think we need what Alan called for, a 'killall' that will slaughter
things in odd pd's.  I notice linux's 'shutdown' binary seems to be the
above script added with a sys5 'killall', all-in-one.


On Nov 25, 2017 1:38 PM, "Tormod Volden" <notifications@github.com> wrote:

Running reboot (also without -f) leaves the filesystem dirty and it will be
mounted read-only on next boot. I can run "remount $ROOTDEVICE ro" before
reboot, and it will be fine. Must this be handled by init scripts, or
should the kernel unmount it cleanly?BTW, after running remount, prtroot
still report rw.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/EtchedPixels/FUZIX/issues/568>, or mute the thread
