### ISSUE TITLE
different architectures for kernel and user?

### ISSUE THREAD

**Issue by jcw** [EtchedPixels/FUZIX#701]
Would it be feasible to compile FUZIX using one architecture (say ARM), whilst user mode is something entirely different (say a Z80)? This scenario would be for an emulator: currently, I can compile the kernel and all utilities for say a Z80, and then run the entire setup inside an emulator - but it might be useful for all sorts of reasons to run the kernel _outside_ the emulated environment.

**Comment by EtchedPixels** [comment]
You could build all of it for ARM I guess.

Youu will need to get the user/kernel types right and alignment matching on structures. If that was done then you would need to make doexec() call into the emulator of the Z80 code instead of jumping into the Z80 code. That leaves fiddly things like signals and task switching but *in theory* yes.

How practical it is - I am not sure.
