### ISSUE TITLE
FUZIX for Macintosh?

### ISSUE THREAD

**Issue by retrac0** [EtchedPixels/FUZIX#789]
Forgive me if this is the wrong place to ask, but would the original 68000 Macs be within FUZIX's scope?  I've lately hacked up a toy bootloader borrowed from Emile & some Toolbox glue with an eye to that end.  It's Mac Plus specific so far, but the 512K/512Ke/SE/Classic could likely be covered together.  

I'm exploring whether ROM routines or native drivers would be the better approach...  The hardware is hairy in spots, particularly the IWM disk.  But keeping things in a Toolbox-friendly state has been challenging... and there is IWM and SCSI code for Linux & BSD already.

If this is on topic, feedback or thoughts would be appreciated.

**Comment by EtchedPixels** [comment]
It ought to be doable. Fuzix for M68K basically wants a flat memory space and some I/O drivers.

It's been a long time but I vaguely remember the original 68000 era macintoshes with shared memory video cannot make the floppy disk timings except from ROM. The hard disk ought to be a bit easier although I wouldn't start from the Linux SCSI code except to see how it's connected up. The Linux driver is fairly scary stuff because it does disconnects and all sorts of funky SCSI layer stuff that quite honestly isn't very useful except for tape drives and CD burning. A simple single command at a time SCSI driver isn't going to be any slower and is a lot lot simpler.

You should be able to plug nothing more than an output driver into a kernel and boot it and get as far as the prompt for a disk device. You'll need a keyboard interface to actually get to type anything but if you set the idle handler up to poll the keyboard as many platforms do anyway you should be able to debug a disk driver and get to load init without an IRQ handler (in fact you can get all the way to a shell prompt it's just that multi-tasking and timed events will fail - including shutdown)
