### ISSUE TITLE
advent: Can't read save file...

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [EtchedPixels/FUZIX#880]
```
# /usr/games/advent

Do you want to restore a saved game? (Y/N) n
Welcome to adventure!!  Would you like instructions?
>no
You are inside a building, a well house for a large spring.

There are some keys on the ground here.
There is a shiny brass lamp nearby.
There is tasty food here.
There is a bottle of water here.
>take lamp
OK

>suspend
What do you want to call the saved game? advsave
Opening save file "advsave".
Game saved.

# ls
advsave
# /usr/games/advent

Do you want to restore a saved game? (Y/N) y
What is your saved game name? advsave

Opening save file "advsave".
Can't read save file...
# 
```

I have tested this with the Raspberry Pi Pico build of FUZIX from https://cowlark.com/2021-03-10-fuzix-pi-pico/index.html (prebuild binaries) and with the emulator https://kmorimatsu.github.io/fuzix/fuzix.html and tomssbc-0.3.ide).
It is the same if I enter absolute instead of relative paths.

**Comment by EtchedPixels** [comment]
This is caused by an assumption in the code that sequential global variables are in order in memory. It may have been true for compilers when the code was written but it aint these days. Needs the save context turning into a structure and then the references globally being switched to structname.whatever

**Comment by EtchedPixels** [comment]
Reworked and fix pushed. The state is now in a struct
