### ISSUE TITLE
'SDCC Notes' wiki page vs. current SDCC

### ISSUE THREAD

**Issue by spth** [EtchedPixels/FUZIX#901]
The 'SDCC Notes' wiki page was last updated in 2015. I think some issues have since been fixed. So it might make sense to check which ones still apply to current SDCC.
The SDCC project is aiming for a 4.2.0 release in late February or early March, so now might be a good time to discover any FUZIX-affecting issues in current SDCC; I guess there is still a chance for bug-fixes before the release.

**Comment by EtchedPixels** [comment]
I don't see anything that has changed at this point.

The ABI changes may improve stuff but they'll also totally break everything in the Fuzix codebase so that would be a huge switchover project for someone to do.

Moving also means porting the compiler and linker patches Fuzix uses because SDCC upstream still lacks usable code banking support.
